[package]
name = "nu_plugin_post"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>", "Jonathan Turner <jonathan.d.turner@gmail.com>", "Andrés N. Robalino <andres@androbtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-protocol = { path = "../nu-protocol" }
nu-source = { path = "../nu-source" }
nu-errors = { path = "../nu-errors" }
futures = { version = "=0.3.1", features = ["compat", "io-compat"] }
surf = "1.0.3"
url = "2.1.0"
serde_json = "1.0.44"
base64 = "0.11"
num-traits = "0.2.10"

[build-dependencies]
nu-build = { version = "0.1.0", path = "../nu-build" }
