complete_from_path = true
ctrlc_exit = false
disable_table_indexes = false
header_align = "l"
header_bold = true
header_color = "c"
nonzero_exit_errors = true
pivot_mode = "auto"
plugin_dirs = ["D:\\Src\\GitHub\\nu-plugin-lib\\samples\\Nu.Plugin.Len\\bin\\Debug\\netcoreapp3.1"]
prompt = "echo [ $(ansi gb) $(pwd) $(ansi reset) \"(\" $(ansi cb) $(do -i { git rev-parse --abbrev-ref HEAD | trim }) $(ansi reset) \")\" $(char newline) $(ansi yb) $(date --format \"%m/%d/%Y %I:%M:%S%.3f %p\" --raw) $(ansi reset) \"> \" ] | str collect"
rm_always_trash = true
startup = [
  "alias la [path] {ls --full $path}",
  "alias nudown [] {fetch https://api.github.com/repos/nushell/nushell/releases | get assets | select name download_count}",
]
table_mode = "other"

[line_editor]
auto_add_history = true 
bell_style = "audible" # audible, none, visible
color_mode = "enabled" # enabled, forced, disabled
completion_prompt_limit = 1 
completion_type = "circular" # circular, list, fuzzy
edit_mode = "vi" # vi, emacs
history_duplicates = "alwaysadd" # alwaysadd,ignoreconsecutive
history_ignore_space = true 
keyseq_timeout_ms = 500 # ms
max_history_size = 100000 
tab_stop = 4 

[textview]
colored_output = true
grid = false
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 4
term_width = "default"
theme = "TwoDark"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "NoWrapping"

# To add path and env do this
# > config set path $nu.path
# > config set env $nu.env
