[package]
name = "nu_plugin_textview"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>", "Jonathan Turner <jonathan.d.turner@gmail.com>", "Andrés N. Robalino <andres@androbtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-protocol = { path = "../nu-protocol" }
nu-source = { path = "../nu-source" }
nu-errors = { path = "../nu-errors" }

crossterm = "0.10.2"
syntect = "3.3.0"
onig_sys = "~69.2.0"
ansi_term = "0.12.1"
url = "2.1.0"

[build-dependencies]
nu-build = { version = "0.1.0", path = "../nu-build" }
