[package]
name = "nu-macros"
version = "0.12.0"
authors = ["The Nu Project Contributors"]
edition = "2018"
description = "Core macros for building Nushell"
license = "MIT"

[lib]
doctest = false

[dependencies]
nu-protocol = { path = "../nu-protocol", version = "0.12.0" }
